{ 
  "text" : "The authenticate function in LDAPUserFolder/LDAPUserFolder.py in zope-ldapuserfolder 2.9-1 does not verify the password for the emergency account, which allows remote attackers to gain privileges.\n" ,
  "entities" : [ { 
    "eid" : "E1" ,
    "keyid" : "DomainName#3598c078cf0412eb8858a47f39754099" ,
    "type" : "DomainName" ,
    "subType" : "DomainName" ,
    "value" : "ldapuserfolder.py" ,
    "begin" : 44 ,
    "end" : 61 ,
    "canonicalForm" : "LDAPUserFolder.py" ,
    "score" : "0.0"
  }
  , { 
    "eid" : "E2" ,
    "keyid" : "ThreatActor#d0f531219210b35f7261f3d6049ee44c" ,
    "type" : "ThreatActor" ,
    "subType" : "ThreatActor" ,
    "value" : "remote attacker" ,
    "begin" : 160 ,
    "end" : 176 ,
    "canonicalForm" : "remote attacker" ,
    "score" : "0.0"
  }
  , { 
    "eid" : "E3" ,
    "keyid" : "TTP#2bc67f1bc2ffc0ad50ab74e2fc45d37a" ,
    "type" : "TTP" ,
    "subType" : "TTP" ,
    "value" : "gain privileges" ,
    "begin" : 180 ,
    "end" : 195 ,
    "canonicalForm" : "gain privileges" ,
    "score" : "0.0"
  }
  ,  ] ,
  "relations" : [  ]
}
