{ 
  "text" : "The (1) Conn_StartLogin and (2) cb_Read_Resolver_Result functions in conn.c in ngIRCd 18 through 20.2, when the configuration option NoticeAuth is enabled, does not properly handle the return code for the Handle_Write function, which allows remote attackers to cause a denial of service (assertion failure and server crash) via unspecified vectors, related to a \"notice auth\" message not being sent to a new client.\n" ,
  "entities" : [ { 
    "eid" : "E1" ,
    "keyid" : "ThreatActor#d0f531219210b35f7261f3d6049ee44c" ,
    "type" : "ThreatActor" ,
    "subType" : "ThreatActor" ,
    "value" : "remote attacker" ,
    "begin" : 241 ,
    "end" : 257 ,
    "canonicalForm" : "remote attacker" ,
    "score" : "0.0"
  }
  , { 
    "eid" : "E2" ,
    "keyid" : "TTP#9c98ef6a7451d6f82ca2194ee23d1acb" ,
    "type" : "TTP" ,
    "subType" : "TTP" ,
    "value" : "denial of service" ,
    "begin" : 269 ,
    "end" : 286 ,
    "canonicalForm" : "denial of service" ,
    "score" : "0.0"
  }
  ,  ] ,
  "relations" : [ { 
    "rid" : "R1" ,
    "type" : "cause" ,
    "predicate" : { 
      "begin" : 258 ,
      "end" : 266 ,
      "surfaceForm" : "to cause"
    }
     ,
    "arguments" : [ { 
      "argnum" : 1 ,
      "begin" : 241 ,
      "end" : 257 ,
      "eid" : "E1" ,
      "canonicalForm" : "remote attacker"
    }
    , { 
      "argnum" : 2 ,
      "begin" : 269 ,
      "end" : 286 ,
      "eid" : "E2" ,
      "canonicalForm" : "denial of service"
    }
    ,  ]
  }
  ,  ]
}
