{ 
  "text" : "Race condition in the FTPHandler class in ftpserver.py in pyftpdlib before 0.5.2 allows remote attackers to cause a denial of service (daemon outage) by establishing and then immediately closing a TCP connection, leading to the accept function having an unexpected value of None for the address, or an ECONNABORTED, EAGAIN, or EWOULDBLOCK error, a related issue to CVE-2010-3492.\n" ,
  "entities" : [ { 
    "eid" : "E1" ,
    "keyid" : "DomainName#4133cb5ec9f73ff9465a56ad062c75e2" ,
    "type" : "DomainName" ,
    "subType" : "DomainName" ,
    "value" : "ftpserver.py" ,
    "begin" : 42 ,
    "end" : 54 ,
    "canonicalForm" : "ftpserver.py" ,
    "score" : "0.0"
  }
  , { 
    "eid" : "E2" ,
    "keyid" : "ThreatActor#d0f531219210b35f7261f3d6049ee44c" ,
    "type" : "ThreatActor" ,
    "subType" : "ThreatActor" ,
    "value" : "remote attacker" ,
    "begin" : 88 ,
    "end" : 104 ,
    "canonicalForm" : "remote attacker" ,
    "score" : "0.0"
  }
  , { 
    "eid" : "E3" ,
    "keyid" : "TTP#9c98ef6a7451d6f82ca2194ee23d1acb" ,
    "type" : "TTP" ,
    "subType" : "TTP" ,
    "value" : "denial of service" ,
    "begin" : 116 ,
    "end" : 133 ,
    "canonicalForm" : "denial of service" ,
    "score" : "0.0"
  }
  , { 
    "eid" : "E4" ,
    "keyid" : "Vulnerability#9971dde2f1ae76e1a6e301bdf91249c0" ,
    "type" : "Vulnerability" ,
    "subType" : "CVE" ,
    "value" : "cve-2010-3492" ,
    "begin" : 365 ,
    "end" : 378 ,
    "canonicalForm" : "CVE-2010-3492" ,
    "score" : "0.0"
  }
  ,  ] ,
  "relations" : [ { 
    "rid" : "R1" ,
    "type" : "relatedEntity" ,
    "predicate" : { } ,
    "arguments" : [ { 
      "argnum" : 1 ,
      "begin" : 42 ,
      "end" : 54 ,
      "eid" : "E1" ,
      "canonicalForm" : "ftpserver.py"
    }
    , { 
      "argnum" : 2 ,
      "begin" : 116 ,
      "end" : 133 ,
      "eid" : "E3" ,
      "canonicalForm" : "denial of service"
    }
    ,  ]
  }
  , { 
    "rid" : "R2" ,
    "type" : "cause" ,
    "predicate" : { 
      "begin" : 105 ,
      "end" : 113 ,
      "surfaceForm" : "to cause"
    }
     ,
    "arguments" : [ { 
      "argnum" : 1 ,
      "begin" : 88 ,
      "end" : 104 ,
      "eid" : "E2" ,
      "canonicalForm" : "remote attacker"
    }
    , { 
      "argnum" : 2 ,
      "begin" : 116 ,
      "end" : 133 ,
      "eid" : "E3" ,
      "canonicalForm" : "denial of service"
    }
    ,  ]
  }
  , { 
    "rid" : "R3" ,
    "type" : "relatedEntity" ,
    "predicate" : { } ,
    "arguments" : [ { 
      "argnum" : 1 ,
      "begin" : 116 ,
      "end" : 133 ,
      "eid" : "E3" ,
      "canonicalForm" : "denial of service"
    }
    , { 
      "argnum" : 2 ,
      "begin" : 365 ,
      "end" : 378 ,
      "eid" : "E4" ,
      "canonicalForm" : "CVE-2010-3492"
    }
    ,  ]
  }
  , { 
    "rid" : "R4" ,
    "type" : "relatedEntity" ,
    "predicate" : { } ,
    "arguments" : [ { 
      "argnum" : 1 ,
      "begin" : 42 ,
      "end" : 54 ,
      "eid" : "E1" ,
      "canonicalForm" : "ftpserver.py"
    }
    , { 
      "argnum" : 2 ,
      "begin" : 365 ,
      "end" : 378 ,
      "eid" : "E4" ,
      "canonicalForm" : "CVE-2010-3492"
    }
    ,  ]
  }
  , { 
    "rid" : "R5" ,
    "type" : "allow" ,
    "predicate" : { 
      "begin" : 81 ,
      "end" : 87 ,
      "surfaceForm" : "allows"
    }
     ,
    "arguments" : [ { 
      "argnum" : 1 ,
      "begin" : 42 ,
      "end" : 54 ,
      "eid" : "E1" ,
      "canonicalForm" : "ftpserver.py"
    }
    , { 
      "argnum" : 2 ,
      "begin" : 88 ,
      "end" : 104 ,
      "eid" : "E2" ,
      "canonicalForm" : "remote attacker"
    }
    ,  ]
  }
  , { 
    "rid" : "R6" ,
    "type" : "relatedEntity" ,
    "predicate" : { } ,
    "arguments" : [ { 
      "argnum" : 1 ,
      "begin" : 88 ,
      "end" : 104 ,
      "eid" : "E2" ,
      "canonicalForm" : "remote attacker"
    }
    , { 
      "argnum" : 2 ,
      "begin" : 365 ,
      "end" : 378 ,
      "eid" : "E4" ,
      "canonicalForm" : "CVE-2010-3492"
    }
    ,  ]
  }
  ,  ]
}
