{ 
  "text" : "A flaw was found in the Linux kernel's ext4 filesystem. A local user can cause an out-of-bound access in ext4_get_group_info function, a denial of service, and a system crash by mounting and operating on a crafted ext4 filesystem image.\n" ,
  "entities" : [ { 
    "eid" : "E1" ,
    "keyid" : "676ea371ef1f86b9e4b86c2d012c901d" ,
    "type" : "MiscEntity" ,
    "subType" : "flaw" ,
    "value" : "flaw" ,
    "begin" : 2 ,
    "end" : 6 ,
    "canonicalForm" : "flaw" ,
    "score" : "0.0"
  }
  , { 
    "eid" : "E2" ,
    "keyid" : "Identity#e206a54e97690cce50cc872dd70ee896" ,
    "type" : "Identity" ,
    "subType" : "Organization" ,
    "value" : "linux" ,
    "begin" : 24 ,
    "end" : 29 ,
    "canonicalForm" : "Linux" ,
    "score" : "0.0"
  }
  , { 
    "eid" : "E3" ,
    "keyid" : "Product#e206a54e97690cce50cc872dd70ee896" ,
    "type" : "Product" ,
    "subType" : "OperatingSystem" ,
    "value" : "linux" ,
    "begin" : 24 ,
    "end" : 29 ,
    "canonicalForm" : "Linux" ,
    "score" : "0.0"
  }
  , { 
    "eid" : "E4" ,
    "keyid" : "TTP#9c98ef6a7451d6f82ca2194ee23d1acb" ,
    "type" : "TTP" ,
    "subType" : "TTP" ,
    "value" : "denial of service" ,
    "begin" : 137 ,
    "end" : 154 ,
    "canonicalForm" : "denial of service" ,
    "score" : "0.0"
  }
  ,  ] ,
  "relations" : [ { 
    "rid" : "R1" ,
    "type" : "found_in" ,
    "predicate" : { 
      "begin" : 11 ,
      "end" : 19 ,
      "surfaceForm" : "found in"
    }
     ,
    "arguments" : [ { 
      "argnum" : 1 ,
      "begin" : 2 ,
      "end" : 6 ,
      "eid" : "E1" ,
      "canonicalForm" : "flaw"
    }
    , { 
      "argnum" : 2 ,
      "begin" : 24 ,
      "end" : 29 ,
      "eid" : "E2" ,
      "canonicalForm" : "Linux"
    }
    ,  ]
  }
  ,  ]
}
