{ 
  "text" : "An issue was discovered in Varnish Cache before 6.0.4 LTS, and 6.1.x and 6.2.x before 6.2.1. An HTTP/1 parsing failure allows a remote attacker to trigger an assert by sending crafted HTTP/1 requests. The assert will cause an automatic restart with a clean cache, which makes it a Denial of Service attack.\n" ,
  "entities" : [ { 
    "eid" : "E1" ,
    "keyid" : "FilePath#aba4e84c84cc8c6b44d5af02ccf77e87" ,
    "type" : "FilePath" ,
    "subType" : "FilePath" ,
    "value" : "/1 parsing failure allows a remote attacker to trigger an assert by sending crafted HTTP/1" ,
    "begin" : 100 ,
    "end" : 190 ,
    "canonicalForm" : "/1 parsing failure allows a remote attacker to trigger an assert by sending crafted HTTP/1" ,
    "score" : "0.0"
  }
  , { 
    "eid" : "E2" ,
    "keyid" : "Campaign#9c98ef6a7451d6f82ca2194ee23d1acb" ,
    "type" : "Campaign" ,
    "subType" : "Campaign" ,
    "value" : "denial of service" ,
    "begin" : 281 ,
    "end" : 305 ,
    "canonicalForm" : "Denial of Service attack" ,
    "score" : "0.0"
  }
  , { 
    "eid" : "E3" ,
    "keyid" : "TTP#9c98ef6a7451d6f82ca2194ee23d1acb" ,
    "type" : "TTP" ,
    "subType" : "TTP" ,
    "value" : "denial of service" ,
    "begin" : 281 ,
    "end" : 298 ,
    "canonicalForm" : "Denial of Service" ,
    "score" : "0.0"
  }
  ,  ] ,
  "relations" : [ { 
    "rid" : "R1" ,
    "type" : "relatedFilePath" ,
    "predicate" : { } ,
    "arguments" : [ { 
      "argnum" : 1 ,
      "begin" : 281 ,
      "end" : 305 ,
      "eid" : "E2" ,
      "canonicalForm" : "Denial of Service attack"
    }
    , { 
      "argnum" : 2 ,
      "begin" : 100 ,
      "end" : 190 ,
      "eid" : "E1" ,
      "canonicalForm" : "/1 parsing failure allows a remote attacker to trigger an assert by sending crafted HTTP/1"
    }
    ,  ]
  }
  ,  ]
}
